// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOL5t8v2pU3ZDpKV98gg6B_rSJ-42Qa4',
    appId: '1:87543980944:web:8ac5a4641a12c107570915',
    messagingSenderId: '87543980944',
    projectId: 'quizapp-5d279',
    authDomain: 'quizapp-5d279.firebaseapp.com',
    storageBucket: 'quizapp-5d279.appspot.com',
    measurementId: 'G-G8Y0NS3DJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDSTbj7I_MlbxlbYyB9exNCgDX-SYQGKY',
    appId: '1:87543980944:android:a274f88d25c46de5570915',
    messagingSenderId: '87543980944',
    projectId: 'quizapp-5d279',
    storageBucket: 'quizapp-5d279.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlWsku5Nsk_bz-P_cFkwl1GybUtxoXI1g',
    appId: '1:87543980944:ios:b7852cf6a9c14631570915',
    messagingSenderId: '87543980944',
    projectId: 'quizapp-5d279',
    storageBucket: 'quizapp-5d279.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlWsku5Nsk_bz-P_cFkwl1GybUtxoXI1g',
    appId: '1:87543980944:ios:c2d933f6a3cee6ca570915',
    messagingSenderId: '87543980944',
    projectId: 'quizapp-5d279',
    storageBucket: 'quizapp-5d279.appspot.com',
    iosBundleId: 'com.example.quizapp.RunnerTests',
  );
}
